
// Code generated by go generate; DO NOT EDIT.
package blathers

func init() {
	var info *teamInfo

	info = TeamInfo["cdc"]
	info.TriageColumnID = 3570120
	info.ProjectID = 1723641
	info = TeamInfo["sql-schema"]
	info.TriageColumnID = 8946818
	info.ProjectID = 3842382
	info = TeamInfo["observability-inf"]
	info.TriageColumnID = 0
	info.ProjectID = 12403058
	info = TeamInfo["storage"]
	info.TriageColumnID = 6668367
	info.ProjectID = 3294634
	info = TeamInfo["server-and-security"]
	info.TriageColumnID = 2521812
	info.ProjectID = 1428339
	info = TeamInfo["bulk-io"]
	info.TriageColumnID = 3097123
	info.ProjectID = 1666762
	info = TeamInfo["kv"]
	info.TriageColumnID = 3550674
	info.ProjectID = 1447869
	info = TeamInfo["sql-experience"]
	info.TriageColumnID = 8532151
	info.ProjectID = 3374358
	info = TeamInfo["sql-queries"]
	info.TriageColumnID = 13549252
	info.ProjectID = 12052721
	info = TeamInfo["sql-observability"]
	info.TriageColumnID = 12618343
	info.ProjectID = 11181516
}
